import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin
from app.models.enums import DevicePairingStatus, DeviceSessionStatus
from app.models.types import GUID

if TYPE_CHECKING:
    from app.models.user import User


class Device(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A paired Android device belonging to one user (Devices / remote control module)."""

    __tablename__ = "devices"

    user_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    name: Mapped[str] = mapped_column(String(150), nullable=False)
    device_fingerprint: Mapped[str] = mapped_column(String(255), nullable=False)
    # Reserved for a future device-bound auth hardening step (e.g. signed
    # challenge-response); unused today, kept so adding it later doesn't
    # require another migration.
    public_key: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    platform: Mapped[str] = mapped_column(String(20), default="android", nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    # Long-lived device credential minted at pairing time, hashed like a
    # refresh token (never stored or re-shown in plaintext after pairing).
    device_secret_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    paired_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    owner: Mapped["User"] = relationship(back_populates="devices")
    sessions: Mapped[list["DeviceSession"]] = relationship(
        back_populates="device", cascade="all, delete-orphan"
    )


class DevicePairingCode(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """
    A short-lived, single-use code generated by an authenticated web session
    and entered on the physical Android device to complete pairing. The
    plaintext code is never persisted — only its hash, mirroring how
    refresh/reset tokens are stored (see core/security.py::hash_token).
    """

    __tablename__ = "device_pairing_codes"

    user_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    code_hash: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    status: Mapped[DevicePairingStatus] = mapped_column(
        String(10), default=DevicePairingStatus.PENDING, nullable=False, index=True
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resulting_device_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID(), ForeignKey("devices.id", ondelete="SET NULL"), nullable=True
    )


class DeviceSession(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """
    One remote-control session: signaling/lifecycle metadata only. The
    session id doubles as the WebRTC signaling channel name — no video,
    audio, or input media is ever persisted or transits the backend.
    """

    __tablename__ = "device_sessions"

    device_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("devices.id", ondelete="CASCADE"), index=True, nullable=False
    )
    # Denormalized alongside device_id so owner-scoped queries don't need a
    # join, matching the rest of the schema's convention.
    user_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    status: Mapped[DeviceSessionStatus] = mapped_column(
        String(10), default=DeviceSessionStatus.PENDING, nullable=False, index=True
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ended_reason: Mapped[str | None] = mapped_column(String(50), nullable=True)
    web_ticket_jti: Mapped[str | None] = mapped_column(String(64), nullable=True)
    device_ticket_jti: Mapped[str | None] = mapped_column(String(64), nullable=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    device: Mapped["Device"] = relationship(back_populates="sessions")
